"""add_courses_and_course_progress_tables

Revision ID: 05d0a6d3a9f6
Revises: fc54cd9daf3d
Create Date: 2025-11-02 13:32:00.283531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05d0a6d3a9f6'
down_revision: Union[str, Sequence[str], None] = 'fc54cd9daf3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('niche_id', sa.UUID(), nullable=False),
    sa.Column('video_link', sa.VARCHAR(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_table('course_additional_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('link', sa.VARCHAR(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_key_takeaways',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_course_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('is_favourite', sa.BOOLEAN(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='unique_user_course')
    )
    op.create_index(op.f('ix_user_course_progress_course_id'), 'user_course_progress', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_course_progress_user_id'), 'user_course_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_course_progress_user_id'), table_name='user_course_progress')
    op.drop_index(op.f('ix_user_course_progress_course_id'), table_name='user_course_progress')
    op.drop_table('user_course_progress')
    op.drop_table('course_key_takeaways')
    op.drop_table('course_additional_resources')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
