"""make_industry_id_nullable_in_users

Revision ID: 7b8a74d630c8
Revises: 33183a1c9085
Create Date: 2025-10-21 19:30:51.754752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b8a74d630c8'
down_revision: Union[str, Sequence[str], None] = '33183a1c9085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'industry_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'industry_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
