"""add_contract_text_to_chats

Revision ID: d7e55dce38bd
Revises: c8cd1c88b506
Create Date: 2025-11-07 19:02:01.560608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7e55dce38bd'
down_revision: Union[str, Sequence[str], None] = 'c8cd1c88b506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('contract_text', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'contract_text')
    # ### end Alembic commands ###
