"""add_cascade_delete_to_foreign_keys

Revision ID: fc54cd9daf3d
Revises: 7b8a74d630c8
Create Date: 2025-10-23 12:53:53.201858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc54cd9daf3d'
down_revision: Union[str, Sequence[str], None] = '7b8a74d630c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('niches_industry_id_fkey'), 'niches', type_='foreignkey')
    op.create_foreign_key(None, 'niches', 'industries', ['industry_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_niches_user_id_fkey'), 'user_niches', type_='foreignkey')
    op.drop_constraint(op.f('user_niches_niche_id_fkey'), 'user_niches', type_='foreignkey')
    op.create_foreign_key(None, 'user_niches', 'niches', ['niche_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_niches', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_niches', type_='foreignkey')
    op.drop_constraint(None, 'user_niches', type_='foreignkey')
    op.create_foreign_key(op.f('user_niches_niche_id_fkey'), 'user_niches', 'niches', ['niche_id'], ['id'])
    op.create_foreign_key(op.f('user_niches_user_id_fkey'), 'user_niches', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'niches', type_='foreignkey')
    op.create_foreign_key(op.f('niches_industry_id_fkey'), 'niches', 'industries', ['industry_id'], ['id'])
    # ### end Alembic commands ###
