"""add_contract_excerpt_to_chats

Revision ID: ff143078010f
Revises: d7e55dce38bd
Create Date: 2025-11-07 21:03:55.955559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff143078010f'
down_revision: Union[str, Sequence[str], None] = 'd7e55dce38bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('contract_excerpt', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'contract_excerpt')
    # ### end Alembic commands ###
